kind: pipeline
type: docker
name: continious_integration

steps:
- name: build
  image: golang:1.18
  environment: 
    TEST: hello
    Ok: world
  commands:
  - export test=$TEST"_"$Ok
  - sed 's/scratch/$test/1' Dockerfile
  - cat Dockerfile
  - echo $test
  - make build
  
- name: publish
  image: plugins/docker
  settings:
    username: sjoshi10
    password:
      from_secret: GH_TOKEN
    storage_driver: overlay
    insecure: true
    registry: ghcr.io
    repo: ghcr.io/sjoshi10/helloworld-web-gen2
    
    force_tag: true
    tags:
    - latest
-----
kind: pipeline
type: docker
name: deployment-staging 

steps:
- name: deploy
  image: sjoshi10/drone-kubectl
  settings:
  environment: 
    AWS_ACCESS_KEY_ID: 
      from_secret: ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: 
      from_secret: SECRET_KEY
  commands:
    - aws s3 ls
    - kubectl config --kubeconfig=default set-context default --cluster=default --namespace=default --user=default
    - aws eks update-kubeconfig --name qn-main-cluster-dev --region us-east-1
    - kubectl get pods
    - kubectl apply -f kubernetes/deployment.yml
    
trigger:
  target:
  - staging
-----    
kind: pipeline
type: docker
name: deployment-prod 

steps:
- name: deploy
  image: sjoshi10/drone-kubectl
  settings:
  environment: 
    AWS_ACCESS_KEY_ID: 
      from_secret: ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: 
      from_secret: SECRET_KEY
  commands:
    - aws s3 ls
    - kubectl config --kubeconfig=default set-context default --cluster=default --namespace=default --user=default
    - aws eks update-kubeconfig --name qn-main-cluster-dev --region us-east-1
    - kubectl get pods
    - kubectl apply -f kubernetes/deployment.yml
    
trigger:
  target:
  - production
