kind: pipeline
type: docker
name: continious_integration

steps:
- name: build
  image: golang:1.18
  commands:
  - make build
  
- name: publish
  image: plugins/docker
  settings:
    storage_driver: overlay
    insecure: true
    registry: ghcr.io
    repo: ghcr.io/sjoshi10/helloworld-web-gen2
    force_tag: true
    tags:
    - latest
  
-------

kind: pipeline
type: docker
name: continuous_deployment

steps:
- name: publish
  image: plugins/docker
  settings:
    storage_driver: overlay
    insecure: true
    registry: 192.168.0.201:5000
    repo: 192.168.0.201:5000/nemonik/helloworld-web
    force_tag: true
    tags:
    - latest

trigger:
  event:
  - tag
