kind: pipeline
type: docker
name: continious_integration

steps:
- name: build
  image: golang:1.18
  commands:
  - make build
  
- name: publish
  image: plugins/docker
  settings:
    username: sjoshi10
    password:
      from_secret: GH_TOKEN
    storage_driver: overlay
    insecure: true
    registry: ghcr.io
    repo: ghcr.io/sjoshi10/helloworld-web-gen2
    
    force_tag: true
    tags:
    - latest
    
- name: deploy
  image: sjoshi10/drone-kubectl
  settings:
  environment: 
    AWS_ACCESS_KEY_ID: 
      from_secret: ACCESS_KEY
    AWS_SECRET_ACCESS_KEY: 
      from_secret: SECRET_KEY
  commands:
    - aws s3 ls
    - kubectl config --kubeconfig=default set-context default --cluster=default --namespace=default --user=default
    - aws eks update-kubeconfig --name qn-main-cluster-dev --region us-east-1
    - kubectl get pods
    - kubectl create deployment my-dep --image=ghcr.io/sjoshi10/helloworld-web-gen2:latest
  
-------

kind: pipeline
type: docker
name: continuous_deployment

steps:
- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server: 
      from_secret: K8S_SERVER
    kubernetes_token:
      from_secret: K8S_TOKEN
    kubernetes_cert:
        from_secret:K8S_CERT
  commands:
    - kubectl create deployment my-dep --image=ghcr.io/sjoshi10/helloworld-web-gen2:latest
  
trigger:
  event:
  - tag
