kind: pipeline
type: docker
name: continious_integration

steps:
- name: build
  image: golang:1.18
  commands:
  - make build
  
- name: publish
  image: plugins/docker
  settings:
    username: sjoshi10
    password:
      from_secret: GH_TOKEN
    storage_driver: overlay
    insecure: true
    registry: ghcr.io
    repo: ghcr.io/sjoshi10/helloworld-web-gen2
    
    force_tag: true
    tags:
    - latest
    
- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server: 
      from_secret: K8S_SERVER
    kubernetes_token:
      from_secret: K8S_TOKEN
    namespace: app
    deployment: my-deployment
    repo: ghcr.io/sjoshi10/
    container: helloworld-web-gen2
    tag: latest
trigger:
  event:
  - tag
  
-------

kind: pipeline
type: docker
name: continuous_deployment

steps:
- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server: 
      from_secret: K8S_SERVER
    kubernetes_token:
      from_secret: K8S_TOKEN
    namespace: app
    deployment: my-deployment
    repo: ghcr.io/sjoshi10/
    container: helloworld-web-gen2
    tag: latest
trigger:
  event:
  - tag
